name: python-ms-template-ci

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build with Gradle
        run: ./gradlew clean build --stacktrace
